foo:
  menus:
    - title: dev
      name: dev
      path: /
    - title: dev
      name: dev
      path: /dev
  compiler:
    timeout: 5
    output-folder: /temp/
  error: /dev/

server:
  port: 8080
  contextPath: /dev