foo:
  menus:
    - title: default
      name: default
      path: /
    - title: default
      name: default
      path: /default
  compiler:
    timeout: 5
    output-folder: /temp/
  error: /default/

