foo:
  menus:
    - title: default
      name: default
      path: /
    - title: default
      name: default
      path: /default
  compiler:
    timeout: 5
    output-folder: /temp/
  error: /default/

spring.datasource:
   url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
   driverClassName: org.h2.Driver
   username: sa
   password:
