foo:
  menus:
    - title: dev
      name: dev
      path: /
    - title: dev
      name: dev
      path: /dev
  compiler:
    timeout: 5
    output-folder: /temp/
  error: /dev/

server:
  port: 8080
  contextPath: /dev

logging:
  level.root: INFO
  file: log/dev.log

spring.jpa.hibernate.ddl-auto: update
spring.jpa.show-sql: true
spring.datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/jpa
  username: root
  password: