foo:
  menus:
    - title: prod
      name: prod
      path: /
    - title: prod
      name: prod
      path: /prod
  compiler:
    timeout: 5
    output-folder: /temp/
  error: /prod/

server:
  port: 8080
  contextPath: /prod

logging:
  level.root: INFO
  level.com.controller: DEBUG
  path: log

spring.jpa.hibernate.ddl-auto: update
spring.jpa.show-sql: true
spring.datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/jpa
  username: root
  password: